---
dist: xenial   # required for Python >= 3.7
language: python
python: "3.7"

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: pypy
      env: TOXENV=pypy
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=pylint
    - python: 3.7
      env: TOXENV=bandit

jobs:
  include:
    - stage: Python tests
      before_script: pip install tox
      script:  tox
    - stage: Terraform tests
      script: test/sanity/terraform_tests.sh
